options:
  formatter: stylish
  merge-default-rules: true
files:
  include: '**/*.s+(a|c)ss'
rules:
  no-color-literals: 2
  property-sort-order: 0
  clean-import-paths: 2
  quotes: 2
  indentation: 1
  no-ids: 0
  no-vendor-prefixes: 0
  no-css-comments: 0
  leading-zero: 0
  pseudo-element: 0
  shorthand-values: 1
  class-name-format: 0
  border-zero: 2
  no-url-protocols: 0
  no-url-domains: 0
  hex-length: 0
  no-duplicate-properties: 2
  no-qualifying-elements: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  no-mergeable-selectors: 2
  mixins-before-declarations: 1
  empty-line-between-blocks: 2
